workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mazen.fireprogram
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.mazen.fireprogram"
        APP_NAME: "Educational Natural Fire program"
        APP_STORE_CONNECT_ISSUER_ID: "e07e7416-7902-48a0-9239-6b66f0ad3cdb"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "5Q78MLL5J3"
        APP_STORE_CONNECT_PRIVATE_KEY: ${APP_STORE_CONNECT_PRIVATE_KEY}
      flutter: stable
    scripts:
      - name: Set up keychain to be used for code signing
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          # Create a temporary directory for the certificates
          mkdir -p $CM_BUILD_DIR/certificates
          
          # Write the private key to a file
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > $CM_BUILD_DIR/certificates/private_key.p8
          
          # Create the provisioning profile if it doesn't exist
          app-store-connect create-app-store-profile \
            --bundle-id="$BUNDLE_ID" \
            --profile-type IOS_APP_STORE \
            --api-key-path="$CM_BUILD_DIR/certificates/private_key.p8" \
            --key-id="$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id="$APP_STORE_CONNECT_ISSUER_ID"
          
          # Fetch signing files
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --api-key-path="$CM_BUILD_DIR/certificates/private_key.p8" \
            --key-id="$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id="$APP_STORE_CONNECT_ISSUER_ID"
          
          # Add certificates to keychain
          keychain add-certificates
          
          # Set up code signing settings on Xcode project
          xcode-project use-profiles --project ios/Runner.xcodeproj
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: ${APP_STORE_CONNECT_PRIVATE_KEY}
        key_id: "5Q78MLL5J3"
        issuer_id: "e07e7416-7902-48a0-9239-6b66f0ad3cdb"
        submit_to_testflight: true
        beta_groups:
          - "Internal" 

          