workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.mazen.fireprogram"
        APP_NAME: "Educational Natural Fire program"
        APP_STORE_CONNECT_ISSUER_ID: "e07e7416-7902-48a0-9239-6b66f0ad3cdb"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "5Q78MLL5J3"
        APP_STORE_CONNECT_PRIVATE_KEY: ${APP_STORE_CONNECT_PRIVATE_KEY}
      flutter: stable
    scripts:
      - name: Set up keychain to be used for code signing
        script: |
          keychain initialize
      - name: Set up code signing
        script: |
          # Create a temporary directory for certificates
          mkdir -p $CM_BUILD_DIR/certificates
          
          # Write the private key to a file (ensuring proper formatting)
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | tr -d '\r' > $CM_BUILD_DIR/certificates/private_key.p8
          
          # Debug: List current certificates and profiles
          app-store-connect list-certificates --private-key="$APP_STORE_CONNECT_PRIVATE_KEY" --key-id="$APP_STORE_CONNECT_KEY_IDENTIFIER" --issuer-id="$APP_STORE_CONNECT_ISSUER_ID"
          app-store-connect list-profiles --private-key="$APP_STORE_CONNECT_PRIVATE_KEY" --key-id="$APP_STORE_CONNECT_KEY_IDENTIFIER" --issuer-id="$APP_STORE_CONNECT_ISSUER_ID"
          
          # Create certificate if needed
          app-store-connect create-certificate \
            --type IOS_DISTRIBUTION \
            --private-key="$APP_STORE_CONNECT_PRIVATE_KEY" \
            --key-id="$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id="$APP_STORE_CONNECT_ISSUER_ID" \
            --save
          
          # Create profile with push notifications enabled
          app-store-connect create-profile \
            --name="$APP_NAME AppStore Profile" \
            --bundle-id="$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --private-key="$APP_STORE_CONNECT_PRIVATE_KEY" \
            --key-id="$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id="$APP_STORE_CONNECT_ISSUER_ID"
          
          # Fetch signing files with push notification entitlements
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --private-key="$APP_STORE_CONNECT_PRIVATE_KEY" \
            --key-id="$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id="$APP_STORE_CONNECT_ISSUER_ID"
          
          # Add certificates to keychain
          keychain add-certificates
          
          # Set up code signing settings on Xcode project
          xcode-project use-profiles
          
          # Enable Push Notifications capability
          xcode-project enable-capabilities \
            --project ios/Runner.xcodeproj \
            --target Runner \
            --capabilities=push
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          # Create export options plist
          cat >> $CM_BUILD_DIR/export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>N4R8LWJ853</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.mazen.fireprogram</key>
                  <string>$APP_NAME AppStore Profile</string>
              </dict>
          </dict>
          </plist>
          EOF
          
          flutter build ipa --release \
            --export-options-plist=$CM_BUILD_DIR/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: ${APP_STORE_CONNECT_PRIVATE_KEY}
        key_id: "5Q78MLL5J3"
        issuer_id: "e07e7416-7902-48a0-9239-6b66f0ad3cdb"
        submit_to_testflight: true
        beta_groups:
          - "Internal" 

          