workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mazen.fireprogram
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.mazen.fireprogram"
        APP_STORE_CONNECT_ISSUER_ID: "e07e7416-7902-48a0-9239-6b66f0ad3cdb"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "5Q78MLL5J3"
        APP_STORE_CONNECT_PRIVATE_KEY: ${APP_STORE_CONNECT_PRIVATE_KEY}
      flutter: stable
    scripts:
      - name: Set up keychain to be used for code signing
        script: |
          keychain initialize
      - name: Set up code signing settings
        script: |
          # Download signing files
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key=@file:/tmp/certificate.p12 \
            --api-key-path="5Q78MLL5J3"
          
          # Set up signing certificate
          keychain add-certificates
          
          # Set up code signing settings on Xcode project
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --project ios/Runner.xcodeproj
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: ${APP_STORE_CONNECT_PRIVATE_KEY}
        key_id: "5Q78MLL5J3"
        issuer_id: "e07e7416-7902-48a0-9239-6b66f0ad3cdb"
        submit_to_testflight: true
        beta_groups:
          - "Internal" 

          